project:
  type: website
  resources: 
    - files/Pelakh_CV.pdf
    - files/Pelakh_Resume.pdf
    - google7e007262b1cf74ea.html
    - _extensions
  preview: 
    browser: true
    port: 4000
  output-dir: _site
  render:
    - "*.qmd"
    - "!README.md"
    

website:
  title: "Avital Pelakh"
  description: "A personal website for Avital Pelakh"
  site-url: "https://apelakh.github.io/"
  open-graph: true
  image: img/2024_Portrait_square.jpg
  image-alt: "Avital Pelakh"
  favicon: img/icon.png
  twitter-card: true
  page-footer: |
    This site was created using Quarto v1.5.57 | source code: [{{< fa brands github >}}](https://github.com/apelakh/apelakh.github.io)<br>
    <i class="bi bi-c-circle"></i> Avital Pelakh 2024 | Contact me at <apelakh@gmail.com>
  navbar:
    pinned: true
    right:
      - icon: house
        href: index.qmd
        text: Home
      - icon: person-lines-fill
        href: about.qmd
      - icon: boxes
        text: Projects
        href: projects
      - icon: newspaper
        href: publications.qmd
        text: Publications & Presentations

format:
  html:
    theme: sandstone
    linkcolor: indianred
    css: styles.css
    smooth-scroll: true
    toc: true
    toc-depth: 2
    link-external-icon: false
    link-external-newwindow: true

editor: source

